WebStaticFilesPath = "web"
CORSAllowedOrigins = []

[AccountManager]
Type = "username-only"

[AccountManager.OAuth2]
Provider = "Google"
RedirectURL = "http://localhost:8080/oauth2callback"

[SecretManager]
Type = ""

[SecretManager.GCP]
OAuth2ClientResourceID = ""

[SecretManager.UNIX]
SecretFilePath = "../secrets.json"

[EncryptionService]
Type = "Fake"
[EncryptionService.GCP_KMS]
KeyName = ""

[DatabaseService]
Type = "InMemory"

[DatabaseService.Spanner]
DatabaseName = "projects/sdv-pdk-test-project1/instances/coast-db/databases/coast-db"

[InstanceManager]
Type = "GCP"
HostOrchestratorProtocol = "http"
AllowSelfSignedHostSSLCertificate = true

[InstanceManager.GCP]
ProjectID = "sdv-pdk-test-project1"
HostImageFamily = ""
HostSnapshot = "projects/sdv-pdk-test-project1/global/snapshots/cf-functional-snapshot-2"
HostOrchestratorPort = 2081
Network = "projects/sdv-pdk-test-project1/global/networks/coast-network"
Subnetwork = "projects/sdv-pdk-test-project1/regions/us-central1/subnetworks/coast-subnetwork"
UseExternalIP = true

[[WebRTC.IceServers]]
URLs = ["stun:stun.l.google.com:19302"]
